  sudo: required
  services:
    - docker
    
  before_install:
    - docker build -t katumalla1234/docker-react -f Dockerfile.dev .  
    
  script:
    - docker run katumalla1234/docker-react npm run test -- --coverage  
    
  deploye:
     provider: elasticbeanstalk
     region: "us-west-2"
     app: "docker-react"
     env: "DockerReact-env"
     bucket_name: "elasticbeanstalk-us-west-2-294412549994"
     bucket_path: "docker-react"
  on:
     branch: master  
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key:
      secure:$AWS_SECRET_KEY
     
     
     
     
     